Smash Magazine Heatmap Project
nusretbutunay/smashmagazine-heatmap pull request #1
Opened 2020-06-19 14:44 UTC by nusretbutunay

This project consists of building a heatmap of the Smashing magazine website

2020-06-19 21:55 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @nusretbutunay and @Maryjanee, great job with this project :+1: Descriptive commit messages :slightly_smiling_face: Linters and validator passed successfully :100: Let us get our project approved by addressing the comments below:

- Kindly replace all divs with the class ```article``` with the ```<article>``` so we can improve the use of HTML semantics
![article](https://user-images.githubusercontent.com/46388113/85181076-97be4100-b274-11ea-8559-1120a9566f52.png)
- Kindly fix the horizontal scroll. A quick fix is to set the main width to 100% so it can fit on all screen
![hroi](https://user-images.githubusercontent.com/46388113/85181768-457e1f80-b276-11ea-9306-d2385407489d.png)
- The rotated image has overlapped with some of the text. Kindly check image below
![pos](https://user-images.githubusercontent.com/46388113/85181448-790c7a00-b275-11ea-9663-b7a6fbd091ce.png)
- The PR and the README description can be improved, kindly edit the PR so we have a descriptive PR. We can check the project requirements for a hint. Example; In this project we did: 1. Positioned elements with float, grid, and flex, etc 
- Kindly fix the author section where we have your social media handles. I could be indentation problem, let us fix it and more our README file more professional

Kindly make these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: :woman_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-21 09:44 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @nusretbutunay  and @Maryjanee ! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There is just one issue that needs to be resolved before you can move on: ⬇️ 
****

- [x] As was requested by the previous TSE, the rotated image is still overlapping with the "community links" text. Please fix this.

![Screen Shot 2020-06-21 at 11 41 28 AM](https://user-images.githubusercontent.com/48804258/85221453-2685a780-b3b4-11ea-869e-1b41c7f532b5.png)
****
### [OPTIONAL]

- While your linters are showing no errors, they are showing some hints. Feel free to use the "Webhint Report" in the linters checks to apply those hints.
![Screen Shot 2020-06-21 at 11 43 43 AM](https://user-images.githubusercontent.com/48804258/85221489-76646e80-b3b4-11ea-8487-dcea5e1beb11.png)

_P.S. all requested changes marked by [OPTIONAL] are not required. It is up to you whether or not you would like to do them_
****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-21 10:54 UTC, tirthajyoti-ghosh approved these changes
# Status: Approved ✔

## Hello @nusretbutunay and @Maryjanee 🖐. You have done an incredible job making this project 🙌👏✨!

## It's a 👍 from me. 

### Before you merge, I would request you consider making these optional changes.

#### [OPTIONAL]

- In `bottom-article-container`, put a border around each of the `article` elements to make it obvious that they are separate.
- In `section.click`, change the color of the texts. It's hard to see right now.
- Increase the height of the footer to match the original.
- There are some invalid CSS property values. Check the comments below.

2020-06-21 10:55 UTC, tirthajyoti-ghosh commented on style.css
> +  box-sizing: 0;
`box-sizing` doesn't accept `0` as its value.

2020-06-21 10:57 UTC, tirthajyoti-ghosh commented on style.css
> +  text-align: left !important;
Remove `!important`. It's a bad practice.

2020-06-21 10:58 UTC, tirthajyoti-ghosh commented on style.css
> +  box-shadow: 0 200px 171 -92px rgba(0, 0, 0, 0.75);
Remember to add units. Unit missing for `171`.

2020-06-21 11:00 UTC, tirthajyoti-ghosh approved these changes
Consider applying these optional changes before merging.

Onto the next project 🚀.

Happy coding 👨‍💻

2020-06-21 11:12 UTC, merged